seed_everything: 16
trainer:
  gradient_clip_val: 1
  logger:
    - class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
      init_args:
        name: SleepApnea
        save_dir: ./logs/tensorboard
  max_epochs: 500
  log_every_n_steps: 8
    
model:
  class_path: source.models.SleepApnea

optimizer:
  class_path: AdamW
  init_args:
    lr: 1e-5

data:
  class_path: source.data.SleepApnea
  init_args:
    data_dir: ./data
    batch_size: 128
    num_workers: 16 
